package requests

type Header struct {
	PannedOrder                                     int      `json:"PlannedOrder"`
	SupplyChainRelationshipID                       int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID               int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID          int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID        *int     `json:"SupplyChainRelationshipProductionPlantID"`
	PlannedOrderType                                string   `json:"PlannedOrderType"`
	Product                                         string   `json:"Product"`
	Buyer                                           int      `json:"Buyer"`
	Seller                                          int      `json:"Seller"`
	DestinationDeliverToParty                       int      `json:"DestinationDeliverToParty"`
	DestinationDeliverToPlant                       string   `json:"DestinationDeliverToPlant"`
	DestinationDeliverToPlantStorageLocation        *string  `json:"DestinationDeliverToPlantStorageLocation"`
	DepartureDeliverFromParty                       int      `json:"DepartureDeliverFromParty"`
	DepartureDeliverFromPlant                       string   `json:"DepartureDeliverFromPlant"`
	DepartureDeliverFromPlantStorageLocation        *string  `json:"DepartureDeliverFromPlantStorageLocation"`
	OwnerProductionPlantBusinessPartner             *int     `json:"OwnerProductionPlantBusinessPartner"`
	OwnerProductionPlant                            *string  `json:"OwnerProductionPlant"`
	OwnerProductionPlantStorageLocation             *string  `json:"OwnerProductionPlantStorageLocation"`
	ProductBaseUnit                                 string   `json:"ProductBaseUnit"`
	MRPArea                                         *string  `json:"MRPArea"`
	MRPController                                   *string  `json:"MRPController"`
	ProductionVersion                               *int     `json:"ProductionVersion"`
	BillOfMaterial                                  *int     `json:"BillOfMaterial"`
	Operations                                      *int     `json:"Operations"`
	PlannedOrderQuantityInBaseUnit                  float32  `json:"PlannedOrderQuantityInBaseUnit"`
	PlannedOrderQuantityInDestinationDeliveryUnit   float32  `json:"PlannedOrderQuantityInDestinationDeliveryUnit"`
	PlannedOrderQuantityInDepartureDeliveryUnit     float32  `json:"PlannedOrderQuantityInDepartureDeliveryUnit"`
	PlannedOrderQuantityInDestinationProductionUnit *float32 `json:"PlannedOrderQuantityInDestinationProductionUnit"`
	PlannedOrderQuantityInDepartureProductionUnit   *float32 `json:"PlannedOrderQuantityInDepartureProductionUnit"`
	PlannedOrderDestinationDeliveryUnit             string   `json:"PlannedOrderDestinationDeliveryUnit"`
	PlannedOrderDepartureDeliveryUnit               string   `json:"PlannedOrderDepartureDeliveryUnit"`
	PlannedOrderDestinationProductionUnit           *string  `json:"PlannedOrderDestinationProductionUnit"`
	PlannedOrderDepartureProductionUnit             *string  `json:"PlannedOrderDepartureProductionUnit"`
	PlannedOrderPlannedScrapQtyInBaseUnit           *float32 `json:"PlannedOrderPlannedScrapQtyInBaseUnit"`
	PlannedOrderPlannedStartDate                    string   `json:"PlannedOrderPlannedStartDate"`
	PlannedOrderPlannedStartTime                    string   `json:"PlannedOrderPlannedStartTime"`
	PlannedOrderPlannedEndDate                      string   `json:"PlannedOrderPlannedEndDate"`
	PlannedOrderPlannedEndTime                      string   `json:"PlannedOrderPlannedEndTime"`
	OrderID                                         *int     `json:"OrderID"`
	OrderItem                                       *int     `json:"OrderItem"`
	Projuct                                         *int     `json:"Projuct"`
	WBSElement                                      *int     `json:"WBSElement"`
	Reservation                                     *int     `json:"Reservation"`
	ReservationItem                                 *int     `json:"ReservationItem"`
	PlannedOrderLongText                            *string  `json:"PlannedOrderLongText"`
	LastScheduledDate                               *string  `json:"LastScheduledDate"`
	ScheduledBasicEndDate                           *string  `json:"ScheduledBasicEndDate"`
	ScheduledBasicEndTime                           *string  `json:"ScheduledBasicEndTime"`
	ScheduledBasicStartDate                         *string  `json:"ScheduledBasicStartDate"`
	ScheduledBasicStartTime                         *string  `json:"ScheduledBasicStartTime"`
	SchedulingType                                  *string  `json:"SchedulingType"`
	PlannedOrderIsReleased                          *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                                    string   `json:"CreationDate"`
	CreationTime                                    string   `json:"CreationTime"`
	LastChangeDate                                  string   `json:"LastChangeDate"`
	LastChangeTime                                  string   `json:"LastChangeTime"`
	IsMarkedForDeletion                             *bool    `json:"IsMarkedForDeletion"`
}
