package requests

type Item struct {
	PlannedOrder                             int      `json:"PlannedOrder"`
	PlannedOrderItem                         int      `json:"PlannedOrderItem"`
	PrecedingProductionOrderItem             *int     `json:"PrecedingProductionOrderItem"`
	FollowingProductionOrderItem             *int     `json:"FollowingProductionOrderItem"`
	SupplyChainRelationshipID                int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID        int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID   int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID *int     `json:"SupplyChainRelationshipProductionPlantID"`
	SupplyChainRelationshipStockConfPlantID  int      `json:"SupplyChainRelationshipStockConfPlantID"`
	PlannedOrderType                         string   `json:"PlannedOrderType"`
	Product                                  string   `json:"Product"`
	Buyer                                    int      `json:"Buyer"`
	Seller                                   int      `json:"Seller"`
	DeliverToParty                           int      `json:"DeliverToParty"`
	DeliverToPlant                           string   `json:"DeliverToPlant"`
	DeliverToPlantStorageLocation            *string  `json:"DeliverToPlantStorageLocation"`
	DeliverFromParty                         int      `json:"DeliverFromParty"`
	DeliverFromPlant                         string   `json:"DeliverFromPlant"`
	DeliverFromPlantStorageLocation          *string  `json:"DeliverFromPlantStorageLocation"`
	ProductionPlantBusinessPartner           int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                          string   `json:"ProductionPlant"`
	ProductionPlantStorageLocation           *string  `json:"ProductionPlantStorageLocation"`
	ProductBaseUnit                          string   `json:"ProductBaseUnit"`
	ProductDeliveryUnit                      string   `json:"ProductDeliveryUnit"`
	ProductProductionUnit                    *string  `json:"ProductProductionUnit"`
	MRPArea                                  *string  `json:"MRPArea"`
	MRPController                            *string  `json:"MRPController"`
	ProductionVersion                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                    *int     `json:"ProductionVersionItem"`
	StockConfirmationBusinessPartner         int      `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                   string   `json:"StockConfirmationPlant"`
	StockConfirmationPlantStorageLocation    *string  `json:"StockConfirmationPlantStorageLocation"`
	BillOfMaterial                           *int     `json:"BillOfMaterial"`
	Operations                               *int     `json:"Operations"`
	PlannedOrderQuantityInBaseUnit           float32  `json:"PlannedOrderQuantityInBaseUnit"`
	PlannedOrderQuantityInDeliveryUnit       float32  `json:"PlannedOrderQuantityInDeliveryUnit"`
	PlannedOrderQuantityInProductionUnit     *float32 `json:"PlannedOrderQuantityInProductionUnit"`
	PlannedOrderPlannedScrapQtyInBaseUnit    *float32 `json:"PlannedOrderPlannedScrapQtyInBaseUnit"`
	PlannedOrderMinimumLotSizeQuantity       float32  `json:"PlannedOrderMinimumLotSizeQuantity"`
	PlannedOrderStandardLotSizeQuantity      float32  `json:"PlannedOrderStandardLotSizeQuantity"`
	PlannedOrderMaximumLotSizeQuantity       float32  `json:"PlannedOrderMaximumLotSizeQuantity"`
	PlannedOrderLotSizeRoundingQuantity      *float32 `json:"PlannedOrderLotSizeRoundingQuantity"`
	PlannedOrderLotSizeIsFixed               *bool    `json:"PlannedOrderLotSizeIsFixed"`
	PlannedOrderPlannedStartDate             string   `json:"PlannedOrderPlannedStartDate"`
	PlannedOrderPlannedStartTime             string   `json:"PlannedOrderPlannedStartTime"`
	PlannedOrderPlannedEndDate               string   `json:"PlannedOrderPlannedEndDate"`
	PlannedOrderPlannedEndTime               string   `json:"PlannedOrderPlannedEndTime"`
	OrderID                                  *int     `json:"OrderID"`
	OrderItem                                *int     `json:"OrderItem"`
	Project                                  *int     `json:"Project"`
	WBSElement                               *int     `json:"WBSElement"`
	Reservation                              *int     `json:"Reservation"`
	ReservationItem                          *int     `json:"ReservationItem"`
	PlannedOrderLongText                     *string  `json:"PlannedOrderLongText"`
	LastScheduledDate                        *string  `json:"LastScheduledDate"`
	ScheduledBasicEndDate                    *string  `json:"ScheduledBasicEndDate"`
	ScheduledBasicEndTime                    *string  `json:"ScheduledBasicEndTime"`
	ScheduledBasicStartDate                  *string  `json:"ScheduledBasicStartDate"`
	ScheduledBasicStartTime                  *string  `json:"ScheduledBasicStartTime"`
	SchedulingType                           *string  `json:"SchedulingType"`
	PlannedOrderIsReleased                   *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                             string   `json:"CreationDate"`
	CreationTime                             string   `json:"CreationTime"`
	LastChangeDate                           string   `json:"LastChangeDate"`
	LastChangeTime                           string   `json:"LastChangeTime"`
	IsMarkedForDeletion                      *bool    `json:"IsMarkedForDeletion"`
}
