package dpfm_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	PlannedOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"business_partner"`
	APISchema     string   `json:"api_schema"`
	Accepter      []string `json:"accepter"`
	MaterialCode  string   `json:"material_code"`
	Plant         string   `json:"plant/supplier"`
	Stock         string   `json:"stock"`
	DocumentType  string   `json:"document_type"`
	DocumentNo    string   `json:"document_no"`
	PlannedDate   string   `json:"planned_date"`
	ValidatedDate string   `json:"validated_date"`
	Deleted       bool     `json:"deleted"`
}

type SDC struct {
	ConnectionKey     string          `json:"connection_key"`
	Result            bool            `json:"result"`
	RedisKey          string          `json:"redis_key"`
	Filepath          string          `json:"filepath"`
	APIStatusCode     int             `json:"api_status_code"`
	RuntimeSessionID  string          `json:"runtime_session_id"`
	BusinessPartnerID *int            `json:"business_partner"`
	ServiceLabel      string          `json:"service_label"`
	APIType           string          `json:"api_type"`
	InputParameters   InputParameters `json:"InputParameters"`
	Header            Header          `json:"PlannedOrder"`
	APISchema         string          `json:"api_schema"`
	Accepter          []string        `json:"accepter"`
	Deleted           bool            `json:"deleted"`
}

type InputParameters struct {
	MRPArea                                 *[]*string `json:"MRPArea"`
	MRPAreaTo                               *string    `json:"MRPAreaTo"`
	MRPAreaFrom                             *string    `json:"MRPAreaFrom"`
	OwnerProductionPlantBusinessPartner     *[]*int    `json:"OwnerProductionPlantBusinessPartner"`
	OwnerProductionPlantBusinessPartnerTo   *int       `json:"OwnerProductionPlantBusinessPartnerTo"`
	OwnerProductionPlantBusinessPartnerFrom *int       `json:"OwnerProductionPlantBusinessPartnerFrom"`
	OwnerProductionPlant                    *[]*string `json:"OwnerProductionPlant"`
	OwnerProductionPlantTo                  *string    `json:"OwnerProductionPlantTo"`
	OwnerProductionPlantFrom                *string    `json:"OwnerProductionPlantFrom"`
	ProductInHeader                         *[]*string `json:"ProductInHeader"`
	ProductInHeaderTo                       *string    `json:"ProductInHeaderTo"`
	ProductInHeaderFrom                     *string    `json:"ProductInHeaderFrom"`
	ProductInItem                           *[]*string `json:"ProductInItem"`
	ProductInItemTo                         *string    `json:"ProductInItemTo"`
	ProductInItemFrom                       *string    `json:"ProductInItemFrom"`
	ProductionPlantBusinessPartner          *[]*int    `json:"ProductionPlantBusinessPartner"`
	ProductionPlantBusinessPartnerTo        *int       `json:"ProductionPlantBusinessPartnerTo"`
	ProductionPlantBusinessPartnerFrom      *int       `json:"ProductionPlantBusinessPartnerFrom"`
	ProductionPlant                         *[]*string `json:"ProductionPlant"`
	ProductionPlantTo                       *string    `json:"ProductionPlantTo"`
	ProductionPlantFrom                     *string    `json:"ProductionPlantFrom"`
	ProductionPlantStorageLocation          *[]*string `json:"ProductionPlantStorageLocation"`
	ProductionPlantStorageLocationTo        *string    `json:"ProductionPlantStorageLocationTo"`
	ProductionPlantStorageLocationFrom      *string    `json:"ProductionPlantStorageLocationFrom"`
	ExecuteProductAvailabilityCheck         *bool      `json:"ExecuteProductAvailabilityCheck"`
	ReleaseProductionOrder                  *bool      `json:"ReleaseProductionOrder"`
}

type Header struct {
	PlannedOrder                                    int       `json:"PlannedOrder"`
	SupplyChainRelationshipID                       int       `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID               int       `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID          int       `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID        *int      `json:"SupplyChainRelationshipProductionPlantID"`
	PlannedOrderType                                string    `json:"PlannedOrderType"`
	Product                                         string    `json:"Product"`
	Buyer                                           int       `json:"Buyer"`
	Seller                                          int       `json:"Seller"`
	DestinationDeliverToParty                       int       `json:"DestinationDeliverToParty"`
	DestinationDeliverToPlant                       string    `json:"DestinationDeliverToPlant"`
	DestinationDeliverToPlantStorageLocation        *string   `json:"DestinationDeliverToPlantStorageLocation"`
	DepartureDeliverFromParty                       int       `json:"DepartureDeliverFromParty"`
	DepartureDeliverFromPlant                       string    `json:"DepartureDeliverFromPlant"`
	DepartureDeliverFromPlantStorageLocation        *string   `json:"DepartureDeliverFromPlantStorageLocation"`
	OwnerProductionPlantBusinessPartner             *int      `json:"OwnerProductionPlantBusinessPartner"`
	OwnerProductionPlant                            *string   `json:"OwnerProductionPlant"`
	OwnerProductionPlantStorageLocation             *string   `json:"OwnerProductionPlantStorageLocation"`
	ProductBaseUnit                                 string    `json:"ProductBaseUnit"`
	MRPArea                                         *string   `json:"MRPArea"`
	MRPController                                   *string   `json:"MRPController"`
	ProductionVersion                               *int      `json:"ProductionVersion"`
	BillOfMaterial                                  *int      `json:"BillOfMaterial"`
	Operations                                      *int      `json:"Operations"`
	PlannedOrderQuantityInBaseUnit                  float32   `json:"PlannedOrderQuantityInBaseUnit"`
	PlannedOrderQuantityInDestinationDeliveryUnit   float32   `json:"PlannedOrderQuantityInDestinationDeliveryUnit"`
	PlannedOrderQuantityInDepartureDeliveryUnit     float32   `json:"PlannedOrderQuantityInDepartureDeliveryUnit"`
	PlannedOrderQuantityInDestinationProductionUnit *float32  `json:"PlannedOrderQuantityInDestinationProductionUnit"`
	PlannedOrderQuantityInDepartureProductionUnit   *float32  `json:"PlannedOrderQuantityInDepartureProductionUnit"`
	PlannedOrderDestinationDeliveryUnit             string    `json:"PlannedOrderDestinationDeliveryUnit"`
	PlannedOrderDepartureDeliveryUnit               string    `json:"PlannedOrderDepartureDeliveryUnit"`
	PlannedOrderDestinationProductionUnit           *string   `json:"PlannedOrderDestinationProductionUnit"`
	PlannedOrderDepartureProductionUnit             *string   `json:"PlannedOrderDepartureProductionUnit"`
	PlannedOrderPlannedScrapQtyInBaseUnit           *float32  `json:"PlannedOrderPlannedScrapQtyInBaseUnit"`
	PlannedOrderPlannedStartDate                    string    `json:"PlannedOrderPlannedStartDate"`
	PlannedOrderPlannedStartTime                    string    `json:"PlannedOrderPlannedStartTime"`
	PlannedOrderPlannedEndDate                      string    `json:"PlannedOrderPlannedEndDate"`
	PlannedOrderPlannedEndTime                      string    `json:"PlannedOrderPlannedEndTime"`
	OrderID                                         *int      `json:"OrderID"`
	OrderItem                                       *int      `json:"OrderItem"`
	Projuct                                         *int      `json:"Projuct"`
	WBSElement                                      *int      `json:"WBSElement"`
	Reservation                                     *int      `json:"Reservation"`
	ReservationItem                                 *int      `json:"ReservationItem"`
	PlannedOrderLongText                            *string   `json:"PlannedOrderLongText"`
	LastScheduledDate                               *string   `json:"LastScheduledDate"`
	ScheduledBasicEndDate                           *string   `json:"ScheduledBasicEndDate"`
	ScheduledBasicEndTime                           *string   `json:"ScheduledBasicEndTime"`
	ScheduledBasicStartDate                         *string   `json:"ScheduledBasicStartDate"`
	ScheduledBasicStartTime                         *string   `json:"ScheduledBasicStartTime"`
	SchedulingType                                  *string   `json:"SchedulingType"`
	PlannedOrderIsReleased                          *bool     `json:"PlannedOrderIsReleased"`
	CreationDate                                    string    `json:"CreationDate"`
	CreationTime                                    string    `json:"CreationTime"`
	LastChangeDate                                  string    `json:"LastChangeDate"`
	LastChangeTime                                  string    `json:"LastChangeTime"`
	IsMarkedForDeletion                             *bool     `json:"IsMarkedForDeletion"`
	Item                                            []Item    `json:"Item"`
	Partner                                         []Partner `json:"Partner"`
	Address                                         []Address `json:"Address"`
}

type HeaderDoc struct {
	PlannedOrder             int     `json:"PlannedOrder"`
	DocType                  string  `json:"DocType"`
	DocVersionID             int     `json:"DocVersionID"`
	DocID                    string  `json:"DocID"`
	FileExtension            *string `json:"FileExtension"`
	FileName                 *string `json:"FileName"`
	FilePath                 *string `json:"FilePath"`
	DocIssuerBusinessPartner *int    `json:"DocIssuerBusinessPartner"`
}

type Item struct {
	PlannedOrder                             int                      `json:"PlannedOrder"`
	PlannedOrderItem                         int                      `json:"PlannedOrderItem"`
	PrecedingProductionOrderItem             *int                     `json:"PrecedingProductionOrderItem"`
	FollowingProductionOrderItem             *int                     `json:"FollowingProductionOrderItem"`
	SupplyChainRelationshipID                int                      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID        int                      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID   int                      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID *int                     `json:"SupplyChainRelationshipProductionPlantID"`
	SupplyChainRelationshipStockConfPlantID  int                      `json:"SupplyChainRelationshipStockConfPlantID"`
	PlannedOrderType                         string                   `json:"PlannedOrderType"`
	Product                                  string                   `json:"Product"`
	Buyer                                    int                      `json:"Buyer"`
	Seller                                   int                      `json:"Seller"`
	DeliverToParty                           int                      `json:"DeliverToParty"`
	DeliverToPlant                           string                   `json:"DeliverToPlant"`
	DeliverToPlantStorageLocation            *string                  `json:"DeliverToPlantStorageLocation"`
	DeliverFromParty                         int                      `json:"DeliverFromParty"`
	DeliverFromPlant                         string                   `json:"DeliverFromPlant"`
	DeliverFromPlantStorageLocation          *string                  `json:"DeliverFromPlantStorageLocation"`
	ProductionPlantBusinessPartner           int                      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                          string                   `json:"ProductionPlant"`
	ProductionPlantStorageLocation           *string                  `json:"ProductionPlantStorageLocation"`
	ProductBaseUnit                          string                   `json:"ProductBaseUnit"`
	ProductDeliveryUnit                      string                   `json:"ProductDeliveryUnit"`
	ProductProductionUnit                    *string                  `json:"ProductProductionUnit"`
	MRPArea                                  *string                  `json:"MRPArea"`
	MRPController                            *string                  `json:"MRPController"`
	ProductionVersion                        *int                     `json:"ProductionVersion"`
	ProductionVersionItem                    *int                     `json:"ProductionVersionItem"`
	StockConfirmationBusinessPartner         int                      `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                   string                   `json:"StockConfirmationPlant"`
	StockConfirmationPlantStorageLocation    *string                  `json:"StockConfirmationPlantStorageLocation"`
	BillOfMaterial                           *int                     `json:"BillOfMaterial"`
	Operations                               *int                     `json:"Operations"`
	PlannedOrderQuantityInBaseUnit           float32                  `json:"PlannedOrderQuantityInBaseUnit"`
	PlannedOrderQuantityInDeliveryUnit       float32                  `json:"PlannedOrderQuantityInDeliveryUnit"`
	PlannedOrderQuantityInProductionUnit     *float32                 `json:"PlannedOrderQuantityInProductionUnit"`
	PlannedOrderPlannedScrapQtyInBaseUnit    *float32                 `json:"PlannedOrderPlannedScrapQtyInBaseUnit"`
	PlannedOrderMinimumLotSizeQuantity       float32                  `json:"PlannedOrderMinimumLotSizeQuantity"`
	PlannedOrderStandardLotSizeQuantity      float32                  `json:"PlannedOrderStandardLotSizeQuantity"`
	PlannedOrderMaximumLotSizeQuantity       float32                  `json:"PlannedOrderMaximumLotSizeQuantity"`
	PlannedOrderLotSizeRoundingQuantity      *float32                 `json:"PlannedOrderLotSizeRoundingQuantity"`
	PlannedOrderLotSizeIsFixed               *bool                    `json:"PlannedOrderLotSizeIsFixed"`
	PlannedOrderPlannedStartDate             string                   `json:"PlannedOrderPlannedStartDate"`
	PlannedOrderPlannedStartTime             string                   `json:"PlannedOrderPlannedStartTime"`
	PlannedOrderPlannedEndDate               string                   `json:"PlannedOrderPlannedEndDate"`
	PlannedOrderPlannedEndTime               string                   `json:"PlannedOrderPlannedEndTime"`
	OrderID                                  *int                     `json:"OrderID"`
	OrderItem                                *int                     `json:"OrderItem"`
	Project                                  *int                     `json:"Project"`
	WBSElement                               *int                     `json:"WBSElement"`
	Reservation                              *int                     `json:"Reservation"`
	ReservationItem                          *int                     `json:"ReservationItem"`
	PlannedOrderLongText                     *string                  `json:"PlannedOrderLongText"`
	LastScheduledDate                        *string                  `json:"LastScheduledDate"`
	ScheduledBasicEndDate                    *string                  `json:"ScheduledBasicEndDate"`
	ScheduledBasicEndTime                    *string                  `json:"ScheduledBasicEndTime"`
	ScheduledBasicStartDate                  *string                  `json:"ScheduledBasicStartDate"`
	ScheduledBasicStartTime                  *string                  `json:"ScheduledBasicStartTime"`
	SchedulingType                           *string                  `json:"SchedulingType"`
	PlannedOrderIsReleased                   *bool                    `json:"PlannedOrderIsReleased"`
	CreationDate                             string                   `json:"CreationDate"`
	CreationTime                             string                   `json:"CreationTime"`
	LastChangeDate                           string                   `json:"LastChangeDate"`
	LastChangeTime                           string                   `json:"LastChangeTime"`
	IsMarkedForDeletion                      *bool                    `json:"IsMarkedForDeletion"`
	ItemComponent                            []ItemComponent          `json:"ItemComponent"`
	ItemOperation                            []ItemOperation          `json:"ItemOperation"`
	ItemOperationComponent                   []ItemOperationComponent `json:"ItemOperationComponent"`
}

type ItemDoc struct {
	PlannedOrder             int     `json:"PlannedOrder"`
	PlannedOrderItem         int     `json:"PlannedOrderItem"`
	DocType                  string  `json:"DocType"`
	DocVersionID             int     `json:"DocVersionID"`
	DocID                    string  `json:"DocID"`
	FileExtension            *string `json:"FileExtension"`
	FileName                 *string `json:"FileName"`
	FilePath                 *string `json:"FilePath"`
	DocIssuerBusinessPartner *int    `json:"DocIssuerBusinessPartner"`
}

type ItemComponent struct {
	PlannedOrder                                   int      `json:"PlannedOrder"`
	PlannedOrderItem                               int      `json:"PlannedOrderItem"`
	BillOfMaterial                                 int      `json:"BillOfMaterial"`
	BillOfMaterialItem                             int      `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                      *int     `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID              *int     `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID         *int     `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipStockConfPlantID        *int     `json:"SupplyChainRelationshipStockConfPlantID"`
	ProductionPlantBusinessPartner                 *int     `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                *string  `json:"ProductionPlant"`
	ComponentProduct                               *string  `json:"ComponentProduct"`
	ComponentProductBuyer                          *int     `json:"ComponentProductBuyer"`
	ComponentProductSeller                         *int     `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                 *int     `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                 *string  `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty               *int     `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant               *string  `json:"ComponentProductDeliverFromPlant"`
	ComponentProductRequirementDate                *string  `json:"ComponentProductRequirementDate"`
	ComponentProductRequirementTime                *string  `json:"ComponentProductRequirementTime"`
	ComponentProductRequiredQuantityInBaseUnit     *float32 `json:"ComponentProductRequiredQuantityInBaseUnit"`
	ComponentProductRequiredQuantityInDeliveryUnit *float32 `json:"ComponentProductRequiredQuantityInDeliveryUnit"`
	ComponentProductPlannedScrapInPercent          *float32 `json:"ComponentProductPlannedScrapInPercent"`
	ComponentProductBaseUnit                       *string  `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                   *string  `json:"ComponentProductDeliveryUnit"`
	ComponentProductIsMarkedForBackflush           *bool    `json:"ComponentProductIsMarkedForBackflush"`
	BillOfMaterialItemText                         *string  `json:"BillOfMaterialItemText"`
	StockConfirmationBusinessPartner               *int     `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                         *string  `json:"StockConfirmationPlant"`
	StockConfirmationPlantStorageLocation          *string  `json:"StockConfirmationPlantStorageLocation"`
	MRPArea                                        *string  `json:"MRPArea"`
	MRPController                                  *string  `json:"MRPController"`
	ProductionVersion                              *int     `json:"ProductionVersion"`
	ProductionVersionItem                          *int     `json:"ProductionVersionItem"`
	ComponentProductBatch                          *string  `json:"ComponentProductBatch"`
	ComponentProductBatchValidityStartDate         *string  `json:"ComponentProductBatchValidityStartDate"`
	ComponentProductBatchValidityStartTime         *string  `json:"ComponentProductBatchValidityStartTime"`
	ComponentProductBatchValidityEndDate           *string  `json:"ComponentProductBatchValidityEndDate"`
	ComponentProductBatchValidityEndTime           *string  `json:"ComponentProductBatchValidityEndTime"`
	ComponentProductCostingPolicy                  *string  `json:"ComponentProductCostingPolicy"`
	ComponentProductPriceUnitQty                   *int     `json:"ComponentProductPriceUnitQty"`
	ComponentProductStandardPrice                  *float32 `json:"ComponentProductStandardPrice"`
	ComponentProductMovingAveragePrice             *float32 `json:"ComponentProductMovingAveragePrice"`
	ComponentProductWithdrawnQuantity              *float32 `json:"ComponentProductWithdrawnQuantity"`
	CreationDate                                   *string  `json:"CreationDate"`
	CreationTime                                   *string  `json:"CreationTime"`
	LastChangeDate                                 *string  `json:"LastChangeDate"`
	LastChangeTime                                 *string  `json:"LastChangeTime"`
	ComponentProductAvailabilityIsNotChecked       *bool    `json:"ComponentProductAvailabilityIsNotChecked"`
	IsMarkedForDeletion                            *bool    `json:"IsMarkedForDeletion"`
}

type ItemOperation struct {
	PlannedOrder                             int      `json:"PlannedOrder"`
	PlannedOrderItem                         int      `json:"PlannedOrderItem"`
	Operations                               int      `json:"Operations"`
	OperationsItem                           int      `json:"OperationsItem"`
	OperationID                              int      `json:"OperationID"`
	SupplyChainRelationshipID                int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID        int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID   int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID int      `json:"SupplyChainRelationshipProductionPlantID"`
	Product                                  string   `json:"Product"`
	Buyer                                    int      `json:"Buyer"`
	Seller                                   int      `json:"Seller"`
	DeliverToParty                           int      `json:"DeliverToParty"`
	DeliverToPlant                           string   `json:"DeliverToPlant"`
	DeliverFromParty                         int      `json:"DeliverFromParty"`
	DeliverFromPlant                         string   `json:"DeliverFromPlant"`
	ProductionPlantBusinessPartner           int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                          string   `json:"ProductionPlant"`
	MRPArea                                  *string  `json:"MRPArea"`
	MRPController                            *string  `json:"MRPController"`
	ProductionVersion                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                    *int     `json:"ProductionVersionItem"`
	Sequence                                 int      `json:"Sequence"`
	SequenceText                             *string  `json:"SequenceText"`
	OperationText                            string   `json:"OperationText"`
	ProductBaseUnit                          string   `json:"ProductBaseUnit"`
	ProductProductionUnit                    string   `json:"ProductProductionUnit"`
	ProductOperationUnit                     string   `json:"ProductOperationUnit"`
	ProductDeliveryUnit                      string   `json:"ProductDeliveryUnit"`
	StandardLotSizeQuantity                  float32  `json:"StandardLotSizeQuantity"`
	MinimumLotSizeQuantity                   float32  `json:"MinimumLotSizeQuantity"`
	MaximumLotSizeQuantity                   float32  `json:"MaximumLotSizeQuantity"`
	OperationPlannedQuantityInBaseUnit       float32  `json:"OperationPlannedQuantityInBaseUnit"`
	OperationPlannedQuantityInProductionUnit float32  `json:"OperationPlannedQuantityInProductionUnit"`
	OperationPlannedQuantityInOperationUnit  float32  `json:"OperationPlannedQuantityInOperationUnit"`
	OperationPlannedQuantityInDeliveryUnit   float32  `json:"OperationPlannedQuantityInDeliveryUnit"`
	OperationPlannedScrapInPercent           *float32 `json:"OperationPlannedScrapInPercent"`
	ResponsiblePlannerGroup                  *string  `json:"ResponsiblePlannerGroup"`
	PlainLongText                            *string  `json:"PlainLongText"`
	WorkCenter                               *int     `json:"WorkCenter"`
	CapacityCategory                         *string  `json:"CapacityCategory"`
	OperationCostingRelevancyType            *string  `json:"OperationCostingRelevancyType"`
	OperationSetupType                       *string  `json:"OperationSetupType"`
	OperationSetupGroupCategory              *string  `json:"OperationSetupGroupCategory"`
	OperationSetupGroup                      *string  `json:"OperationSetupGroup"`
	MaximumWaitDuration                      *float32 `json:"MaximumWaitDuration"`
	StandardWaitDuration                     *float32 `json:"StandardWaitDuration"`
	MinimumWaitDuration                      *float32 `json:"MinimumWaitDuration"`
	WaitDurationUnit                         *string  `json:"WaitDurationUnit"`
	MaximumQueDuration                       *float32 `json:"MaximumQueDuration"`
	StandardQueueDuration                    *float32 `json:"StandardQueueDuration"`
	MinimumQueueDuration                     *float32 `json:"MinimumQueueDuration"`
	QueDurationUnit                          *string  `json:"QueDurationUnit"`
	MaximumMoveDuration                      *float32 `json:"MaximumMoveDuration"`
	StandardMoveDuration                     *float32 `json:"StandardMoveDuration"`
	MinimumMoveDuration                      *float32 `json:"MinimumMoveDuration"`
	MoveDurationUnit                         *string  `json:"MoveDurationUnit"`
	StandardDeliveryDuration                 *float32 `json:"StandardDeliveryDuration"`
	StandardDeliveryDurationUnit             *string  `json:"StandardDeliveryDurationUnit"`
	CostElement                              *string  `json:"CostElement"`
	PlannedOrderIsReleased                   *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                             string   `json:"CreationDate"`
	CreationTime                             string   `json:"CreationTime"`
	LastChangeDate                           string   `json:"LastChangeDate"`
	LastChangeTime                           string   `json:"LastChangeTime"`
	IsMarkedForDeletion                      *bool    `json:"IsMarkedForDeletion"`
}

type ItemOperationComponent struct {
	PlannedOrder                                             int      `json:"PlannedOrder"`
	PlannedOrderItem                                         int      `json:"PlannedOrderItem"`
	Operations                                               int      `json:"Operations"`
	OperationsItem                                           int      `json:"OperationsItem"`
	OperationID                                              int      `json:"OperationID"`
	BillOfMaterial                                           int      `json:"BillOfMaterial"`
	BillOfMaterialItem                                       int      `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                                *int     `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID                        *int     `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID                   *int     `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionPlantBusinessPartner                           *int     `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                          *string  `json:"ProductionPlant"`
	ComponentProduct                                         *string  `json:"ComponentProduct"`
	ComponentProductBuyer                                    *int     `json:"ComponentProductBuyer"`
	ComponentProductSeller                                   *int     `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                           *int     `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                           *string  `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty                         *int     `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant                         *string  `json:"ComponentProductDeliverFromPlant"`
	ComponentProductDeliverToPartyInOperation                *int     `json:"ComponentProductDeliverToPartyInOperation"`
	ComponentProductDeliverToPlantInOperation                *string  `json:"ComponentProductDeliverToPlantInOperation"`
	ComponentProductDeliverFromPartyInOperation              *int     `json:"ComponentProductDeliverFromPartyInOperation"`
	ComponentProductDeliverFromPlantInOperation              *string  `json:"ComponentProductDeliverFromPlantInOperation"`
	ComponentProductRequirementDateInOperation               *string  `json:"ComponentProductRequirementDateInOperation"`
	ComponentProductRequirementTimeInOperation               *string  `json:"ComponentProductRequirementTimeInOperation"`
	ComponentProductPlannedQuantityInBaseUnitInOperation     *float32 `json:"ComponentProductPlannedQuantityInBaseUnitInOperation"`
	ComponentProductPlannedQuantityInDeliveryUnitInOperation *float32 `json:"ComponentProductPlannedQuantityInDeliveryUnitInOperation"`
	ComponentProductPlannedScrapInPercentInOperation         *float32 `json:"ComponentProductPlannedScrapInPercentInOperation"`
	ComponentProductBaseUnit                                 *string  `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                             *string  `json:"ComponentProductDeliveryUnit"`
	ComponentProductIsMarkedForBackflush                     *bool    `json:"ComponentProductIsMarkedForBackflush"`
	MRPArea                                                  *string  `json:"MRPArea"`
	MRPController                                            *string  `json:"MRPController"`
	ProductionVersion                                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                                    *int     `json:"ProductionVersionItem"`
	ComponentProductReservation                              *int     `json:"ComponentProductReservation"`
	ComponentProductReservationItem                          *int     `json:"ComponentProductReservationItem"`
	PlannedOrderIsReleased                                   *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                                             *string  `json:"CreationDate"`
	CreationTime                                             *string  `json:"CreationTime"`
	LastChangeDate                                           *string  `json:"LastChangeDate"`
	LastChangeTime                                           *string  `json:"LastChangeTime"`
	IsMarkedForDeletion                                      *bool    `json:"IsMarkedForDeletion"`
}

type Partner struct {
	PlannedOrder            int     `json:"PlannedOrder"`
	PartnerFunction         string  `json:"PartnerFunction"`
	BusinessPartner         int     `json:"BusinessPartner"`
	BusinessPartnerFullName *string `json:"BusinessPartnerFullName"`
	BusinessPartnerName     *string `json:"BusinessPartnerName"`
	Organization            *string `json:"Organization"`
	Country                 *string `json:"Country"`
	Language                *string `json:"Language"`
	Currency                *string `json:"Currency"`
	ExternalDocumentID      *string `json:"ExternalDocumentID"`
	AddressID               *int    `json:"AddressID"`
}

type Address struct {
	PlannedOrder int    `json:"PlannedOrder"`
	AddressID    int    `json:"AddressID"`
	PostalCode   string `json:"PostalCode"`
	LocalRegion  string `json:"LocalRegion"`
	Country      string `json:"Country"`
	District     string `json:"District"`
	StreetName   string `json:"StreetName"`
	CityName     string `json:"CityName"`
	Building     string `json:"Building"`
	Floor        int    `json:"Floor"`
	Room         int    `json:"Room"`
}
