package dpfm_api_output_formatter

type SDC struct {
	ConnectionKey       string      `json:"connection_key"`
	Result              bool        `json:"result"`
	RedisKey            string      `json:"redis_key"`
	Filepath            string      `json:"filepath"`
	APIStatusCode       int         `json:"api_status_code"`
	RuntimeSessionID    string      `json:"runtime_session_id"`
	BusinessPartnerID   *int        `json:"business_partner"`
	ServiceLabel        string      `json:"service_label"`
	APIType             string      `json:"api_type"`
	Message             interface{} `json:"message"`
	APISchema           string      `json:"api_schema"`
	Accepter            []string    `json:"accepter"`
	Deleted             bool        `json:"deleted"`
	SQLUpdateResult     *bool       `json:"sql_update_result"`
	SQLUpdateError      string      `json:"sql_update_error"`
	SubfuncResult       *bool       `json:"subfunc_result"`
	SubfuncError        string      `json:"subfunc_error"`
	ExconfResult        *bool       `json:"exconf_result"`
	ExconfError         string      `json:"exconf_error"`
	APIProcessingResult *bool       `json:"api_processing_result"`
	APIProcessingError  string      `json:"api_processing_error"`
}

type Message struct {
	Header                 *[]Header                 `json:"Header"`
	Item                   *[]Item                   `json:"Item"`
	ItemComponent          *[]ItemComponent          `json:"ItemComponent"`
	ItemOperation          *[]ItemOperation          `json:"ItemOperation"`
	ItemOperationComponent *[]ItemOperationComponent `json:"ItemOperationComponent"`
}

type Header struct {
	PlannedOrder                                    int      `json:"PlannedOrder"`
	SupplyChainRelationshipID                       int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID               int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID          int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID        *int     `json:"SupplyChainRelationshipProductionPlantID"`
	PlannedOrderType                                string   `json:"PlannedOrderType"`
	Product                                         string   `json:"Product"`
	Buyer                                           int      `json:"Buyer"`
	Seller                                          int      `json:"Seller"`
	DestinationDeliverToParty                       int      `json:"DestinationDeliverToParty"`
	DestinationDeliverToPlant                       string   `json:"DestinationDeliverToPlant"`
	DestinationDeliverToPlantStorageLocation        *string  `json:"DestinationDeliverToPlantStorageLocation"`
	DepartureDeliverFromParty                       int      `json:"DepartureDeliverFromParty"`
	DepartureDeliverFromPlant                       string   `json:"DepartureDeliverFromPlant"`
	DepartureDeliverFromPlantStorageLocation        *string  `json:"DepartureDeliverFromPlantStorageLocation"`
	OwnerProductionPlantBusinessPartner             *int     `json:"OwnerProductionPlantBusinessPartner"`
	OwnerProductionPlant                            *string  `json:"OwnerProductionPlant"`
	OwnerProductionPlantStorageLocation             *string  `json:"OwnerProductionPlantStorageLocation"`
	ProductBaseUnit                                 string   `json:"ProductBaseUnit"`
	MRPArea                                         *string  `json:"MRPArea"`
	MRPController                                   *string  `json:"MRPController"`
	ProductionVersion                               *int     `json:"ProductionVersion"`
	BillOfMaterial                                  *int     `json:"BillOfMaterial"`
	Operations                                      *int     `json:"Operations"`
	PlannedOrderQuantityInBaseUnit                  float32  `json:"PlannedOrderQuantityInBaseUnit"`
	PlannedOrderQuantityInDestinationDeliveryUnit   float32  `json:"PlannedOrderQuantityInDestinationDeliveryUnit"`
	PlannedOrderQuantityInDepartureDeliveryUnit     float32  `json:"PlannedOrderQuantityInDepartureDeliveryUnit"`
	PlannedOrderQuantityInDestinationProductionUnit *float32 `json:"PlannedOrderQuantityInDestinationProductionUnit"`
	PlannedOrderQuantityInDepartureProductionUnit   *float32 `json:"PlannedOrderQuantityInDepartureProductionUnit"`
	PlannedOrderDestinationDeliveryUnit             string   `json:"PlannedOrderDestinationDeliveryUnit"`
	PlannedOrderDepartureDeliveryUnit               string   `json:"PlannedOrderDepartureDeliveryUnit"`
	PlannedOrderDestinationProductionUnit           *string  `json:"PlannedOrderDestinationProductionUnit"`
	PlannedOrderDepartureProductionUnit             *string  `json:"PlannedOrderDepartureProductionUnit"`
	PlannedOrderPlannedScrapQtyInBaseUnit           *float32 `json:"PlannedOrderPlannedScrapQtyInBaseUnit"`
	PlannedOrderPlannedStartDate                    string   `json:"PlannedOrderPlannedStartDate"`
	PlannedOrderPlannedStartTime                    string   `json:"PlannedOrderPlannedStartTime"`
	PlannedOrderPlannedEndDate                      string   `json:"PlannedOrderPlannedEndDate"`
	PlannedOrderPlannedEndTime                      string   `json:"PlannedOrderPlannedEndTime"`
	OrderID                                         *int     `json:"OrderID"`
	OrderItem                                       *int     `json:"OrderItem"`
	Projuct                                         *int     `json:"Projuct"`
	WBSElement                                      *int     `json:"WBSElement"`
	Reservation                                     *int     `json:"Reservation"`
	ReservationItem                                 *int     `json:"ReservationItem"`
	PlannedOrderLongText                            *string  `json:"PlannedOrderLongText"`
	LastScheduledDate                               *string  `json:"LastScheduledDate"`
	ScheduledBasicEndDate                           *string  `json:"ScheduledBasicEndDate"`
	ScheduledBasicEndTime                           *string  `json:"ScheduledBasicEndTime"`
	ScheduledBasicStartDate                         *string  `json:"ScheduledBasicStartDate"`
	ScheduledBasicStartTime                         *string  `json:"ScheduledBasicStartTime"`
	SchedulingType                                  *string  `json:"SchedulingType"`
	PlannedOrderIsReleased                          *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                                    string   `json:"CreationDate"`
	CreationTime                                    string   `json:"CreationTime"`
	LastChangeDate                                  string   `json:"LastChangeDate"`
	LastChangeTime                                  string   `json:"LastChangeTime"`
	IsMarkedForDeletion                             *bool    `json:"IsMarkedForDeletion"`
}

type HeaderDoc struct {
	PlannedOrder             int     `json:"PlannedOrder"`
	DocType                  string  `json:"DocType"`
	DocVersionID             int     `json:"DocVersionID"`
	DocID                    string  `json:"DocID"`
	FileExtension            string  `json:"FileExtension"`
	FileName                 *string `json:"FileName"`
	FilePath                 *string `json:"FilePath"`
	DocIssuerBusinessPartner *int    `json:"DocIssuerBusinessPartner"`
}

type Item struct {
	PlannedOrder                             int      `json:"PlannedOrder"`
	PlannedOrderItem                         int      `json:"PlannedOrderItem"`
	PrecedingProductionOrderItem             *int     `json:"PrecedingProductionOrderItem"`
	FollowingProductionOrderItem             *int     `json:"FollowingProductionOrderItem"`
	SupplyChainRelationshipID                int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID        int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID   int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID *int     `json:"SupplyChainRelationshipProductionPlantID"`
	SupplyChainRelationshipStockConfPlantID  int      `json:"SupplyChainRelationshipStockConfPlantID"`
	PlannedOrderType                         string   `json:"PlannedOrderType"`
	Product                                  string   `json:"Product"`
	Buyer                                    int      `json:"Buyer"`
	Seller                                   int      `json:"Seller"`
	DeliverToParty                           int      `json:"DeliverToParty"`
	DeliverToPlant                           string   `json:"DeliverToPlant"`
	DeliverToPlantStorageLocation            *string  `json:"DeliverToPlantStorageLocation"`
	DeliverFromParty                         int      `json:"DeliverFromParty"`
	DeliverFromPlant                         string   `json:"DeliverFromPlant"`
	DeliverFromPlantStorageLocation          *string  `json:"DeliverFromPlantStorageLocation"`
	ProductionPlantBusinessPartner           int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                          string   `json:"ProductionPlant"`
	ProductionPlantStorageLocation           *string  `json:"ProductionPlantStorageLocation"`
	ProductBaseUnit                          string   `json:"ProductBaseUnit"`
	ProductDeliveryUnit                      string   `json:"ProductDeliveryUnit"`
	ProductProductionUnit                    *string  `json:"ProductProductionUnit"`
	MRPArea                                  *string  `json:"MRPArea"`
	MRPController                            *string  `json:"MRPController"`
	ProductionVersion                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                    *int     `json:"ProductionVersionItem"`
	StockConfirmationBusinessPartner         int      `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                   string   `json:"StockConfirmationPlant"`
	StockConfirmationPlantStorageLocation    *string  `json:"StockConfirmationPlantStorageLocation"`
	BillOfMaterial                           *int     `json:"BillOfMaterial"`
	Operations                               *int     `json:"Operations"`
	PlannedOrderQuantityInBaseUnit           float32  `json:"PlannedOrderQuantityInBaseUnit"`
	PlannedOrderQuantityInDeliveryUnit       float32  `json:"PlannedOrderQuantityInDeliveryUnit"`
	PlannedOrderQuantityInProductionUnit     *float32 `json:"PlannedOrderQuantityInProductionUnit"`
	PlannedOrderPlannedScrapQtyInBaseUnit    *float32 `json:"PlannedOrderPlannedScrapQtyInBaseUnit"`
	PlannedOrderMinimumLotSizeQuantity       float32  `json:"PlannedOrderMinimumLotSizeQuantity"`
	PlannedOrderStandardLotSizeQuantity      float32  `json:"PlannedOrderStandardLotSizeQuantity"`
	PlannedOrderMaximumLotSizeQuantity       float32  `json:"PlannedOrderMaximumLotSizeQuantity"`
	PlannedOrderLotSizeRoundingQuantity      *float32 `json:"PlannedOrderLotSizeRoundingQuantity"`
	PlannedOrderLotSizeIsFixed               *bool    `json:"PlannedOrderLotSizeIsFixed"`
	PlannedOrderPlannedStartDate             string   `json:"PlannedOrderPlannedStartDate"`
	PlannedOrderPlannedStartTime             string   `json:"PlannedOrderPlannedStartTime"`
	PlannedOrderPlannedEndDate               string   `json:"PlannedOrderPlannedEndDate"`
	PlannedOrderPlannedEndTime               string   `json:"PlannedOrderPlannedEndTime"`
	OrderID                                  *int     `json:"OrderID"`
	OrderItem                                *int     `json:"OrderItem"`
	Project                                  *int     `json:"Project"`
	WBSElement                               *int     `json:"WBSElement"`
	Reservation                              *int     `json:"Reservation"`
	ReservationItem                          *int     `json:"ReservationItem"`
	PlannedOrderLongText                     *string  `json:"PlannedOrderLongText"`
	LastScheduledDate                        *string  `json:"LastScheduledDate"`
	ScheduledBasicEndDate                    *string  `json:"ScheduledBasicEndDate"`
	ScheduledBasicEndTime                    *string  `json:"ScheduledBasicEndTime"`
	ScheduledBasicStartDate                  *string  `json:"ScheduledBasicStartDate"`
	ScheduledBasicStartTime                  *string  `json:"ScheduledBasicStartTime"`
	SchedulingType                           *string  `json:"SchedulingType"`
	PlannedOrderIsReleased                   *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                             string   `json:"CreationDate"`
	CreationTime                             string   `json:"CreationTime"`
	LastChangeDate                           string   `json:"LastChangeDate"`
	LastChangeTime                           string   `json:"LastChangeTime"`
	IsMarkedForDeletion                      *bool    `json:"IsMarkedForDeletion"`
}

type ItemDoc struct {
	PlannedOrder             int     `json:"PlannedOrder"`
	PlannedOrderItem         int     `json:"PlannedOrderItem"`
	DocType                  string  `json:"DocType"`
	DocVersionID             int     `json:"DocVersionID"`
	DocID                    string  `json:"DocID"`
	FileExtension            string  `json:"FileExtension"`
	FileName                 *string `json:"FileName"`
	FilePath                 *string `json:"FilePath"`
	DocIssuerBusinessPartner *int    `json:"DocIssuerBusinessPartner"`
}

type ItemComponent struct {
	PlannedOrder                                   int      `json:"PlannedOrder"`
	PlannedOrderItem                               int      `json:"PlannedOrderItem"`
	BillOfMaterial                                 int      `json:"BillOfMaterial"`
	BillOfMaterialItem                             int      `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                      *int     `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID              *int     `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID         *int     `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipStockConfPlantID        *int     `json:"SupplyChainRelationshipStockConfPlantID"`
	ProductionPlantBusinessPartner                 *int     `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                *string  `json:"ProductionPlant"`
	ComponentProduct                               *string  `json:"ComponentProduct"`
	ComponentProductBuyer                          *int     `json:"ComponentProductBuyer"`
	ComponentProductSeller                         *int     `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                 *int     `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                 *string  `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty               *int     `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant               *string  `json:"ComponentProductDeliverFromPlant"`
	ComponentProductRequirementDate                *string  `json:"ComponentProductRequirementDate"`
	ComponentProductRequirementTime                *string  `json:"ComponentProductRequirementTime"`
	ComponentProductRequiredQuantityInBaseUnit     *float32 `json:"ComponentProductRequiredQuantityInBaseUnit"`
	ComponentProductRequiredQuantityInDeliveryUnit *float32 `json:"ComponentProductRequiredQuantityInDeliveryUnit"`
	ComponentProductPlannedScrapInPercent          *float32 `json:"ComponentProductPlannedScrapInPercent"`
	ComponentProductBaseUnit                       *string  `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                   *string  `json:"ComponentProductDeliveryUnit"`
	ComponentProductIsMarkedForBackflush           *bool    `json:"ComponentProductIsMarkedForBackflush"`
	BillOfMaterialItemText                         *string  `json:"BillOfMaterialItemText"`
	StockConfirmationBusinessPartner               *int     `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                         *string  `json:"StockConfirmationPlant"`
	StockConfirmationPlantStorageLocation          *string  `json:"StockConfirmationPlantStorageLocation"`
	MRPArea                                        *string  `json:"MRPArea"`
	MRPController                                  *string  `json:"MRPController"`
	ProductionVersion                              *int     `json:"ProductionVersion"`
	ProductionVersionItem                          *int     `json:"ProductionVersionItem"`
	PlannedOrderIsReleased                         *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                                   *string  `json:"CreationDate"`
	CreationTime                                   *string  `json:"CreationTime"`
	LastChangeDate                                 *string  `json:"LastChangeDate"`
	LastChangeTime                                 *string  `json:"LastChangeTime"`
	IsMarkedForDeletion                            *bool    `json:"IsMarkedForDeletion"`
}

type ItemOperation struct {
	PlannedOrder                             int      `json:"PlannedOrder"`
	PlannedOrderItem                         int      `json:"PlannedOrderItem"`
	Operations                               int      `json:"Operations"`
	OperationsItem                           int      `json:"OperationsItem"`
	OperationID                              int      `json:"OperationID"`
	SupplyChainRelationshipID                int      `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID        int      `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID   int      `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID int      `json:"SupplyChainRelationshipProductionPlantID"`
	Product                                  string   `json:"Product"`
	Buyer                                    int      `json:"Buyer"`
	Seller                                   int      `json:"Seller"`
	DeliverToParty                           int      `json:"DeliverToParty"`
	DeliverToPlant                           string   `json:"DeliverToPlant"`
	DeliverFromParty                         int      `json:"DeliverFromParty"`
	DeliverFromPlant                         string   `json:"DeliverFromPlant"`
	ProductionPlantBusinessPartner           int      `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                          string   `json:"ProductionPlant"`
	MRPArea                                  *string  `json:"MRPArea"`
	MRPController                            *string  `json:"MRPController"`
	ProductionVersion                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                    *int     `json:"ProductionVersionItem"`
	Sequence                                 int      `json:"Sequence"`
	SequenceText                             *string  `json:"SequenceText"`
	OperationText                            string   `json:"OperationText"`
	ProductBaseUnit                          string   `json:"ProductBaseUnit"`
	ProductProductionUnit                    string   `json:"ProductProductionUnit"`
	ProductOperationUnit                     string   `json:"ProductOperationUnit"`
	ProductDeliveryUnit                      string   `json:"ProductDeliveryUnit"`
	StandardLotSizeQuantity                  float32  `json:"StandardLotSizeQuantity"`
	MinimumLotSizeQuantity                   float32  `json:"MinimumLotSizeQuantity"`
	MaximumLotSizeQuantity                   float32  `json:"MaximumLotSizeQuantity"`
	OperationPlannedQuantityInBaseUnit       float32  `json:"OperationPlannedQuantityInBaseUnit"`
	OperationPlannedQuantityInProductionUnit float32  `json:"OperationPlannedQuantityInProductionUnit"`
	OperationPlannedQuantityInOperationUnit  float32  `json:"OperationPlannedQuantityInOperationUnit"`
	OperationPlannedQuantityInDeliveryUnit   float32  `json:"OperationPlannedQuantityInDeliveryUnit"`
	OperationPlannedScrapInPercent           *float32 `json:"OperationPlannedScrapInPercent"`
	ResponsiblePlannerGroup                  *string  `json:"ResponsiblePlannerGroup"`
	PlainLongText                            *string  `json:"PlainLongText"`
	WorkCenter                               *int     `json:"WorkCenter"`
	CapacityCategory                         *string  `json:"CapacityCategory"`
	OperationCostingRelevancyType            *string  `json:"OperationCostingRelevancyType"`
	OperationSetupType                       *string  `json:"OperationSetupType"`
	OperationSetupGroupCategory              *string  `json:"OperationSetupGroupCategory"`
	OperationSetupGroup                      *string  `json:"OperationSetupGroup"`
	MaximumWaitDuration                      *float32 `json:"MaximumWaitDuration"`
	StandardWaitDuration                     *float32 `json:"StandardWaitDuration"`
	MinimumWaitDuration                      *float32 `json:"MinimumWaitDuration"`
	WaitDurationUnit                         *string  `json:"WaitDurationUnit"`
	MaximumQueDuration                       *float32 `json:"MaximumQueDuration"`
	StandardQueueDuration                    *float32 `json:"StandardQueueDuration"`
	MinimumQueueDuration                     *float32 `json:"MinimumQueueDuration"`
	QueDurationUnit                          *string  `json:"QueDurationUnit"`
	MaximumMoveDuration                      *float32 `json:"MaximumMoveDuration"`
	StandardMoveDuration                     *float32 `json:"StandardMoveDuration"`
	MinimumMoveDuration                      *float32 `json:"MinimumMoveDuration"`
	MoveDurationUnit                         *string  `json:"MoveDurationUnit"`
	StandardDeliveryDuration                 *float32 `json:"StandardDeliveryDuration"`
	StandardDeliveryDurationUnit             *string  `json:"StandardDeliveryDurationUnit"`
	CostElement                              *string  `json:"CostElement"`
	PlannedOrderIsReleased                   *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                             string   `json:"CreationDate"`
	CreationTime                             string   `json:"CreationTime"`
	LastChangeDate                           string   `json:"LastChangeDate"`
	LastChangeTime                           string   `json:"LastChangeTime"`
	IsMarkedForDeletion                      *bool    `json:"IsMarkedForDeletion"`
}

type ItemOperationComponent struct {
	PlannedOrder                                             int      `json:"PlannedOrder"`
	PlannedOrderItem                                         int      `json:"PlannedOrderItem"`
	Operations                                               int      `json:"Operations"`
	OperationsItem                                           int      `json:"OperationsItem"`
	OperationID                                              int      `json:"OperationID"`
	BillOfMaterial                                           int      `json:"BillOfMaterial"`
	BillOfMaterialItem                                       int      `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                                *int     `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID                        *int     `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID                   *int     `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionPlantBusinessPartner                           *int     `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                          *string  `json:"ProductionPlant"`
	ComponentProduct                                         *string  `json:"ComponentProduct"`
	ComponentProductBuyer                                    *int     `json:"ComponentProductBuyer"`
	ComponentProductSeller                                   *int     `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                           *int     `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                           *string  `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty                         *int     `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant                         *string  `json:"ComponentProductDeliverFromPlant"`
	ComponentProductDeliverToPartyInOperation                *int     `json:"ComponentProductDeliverToPartyInOperation"`
	ComponentProductDeliverToPlantInOperation                *string  `json:"ComponentProductDeliverToPlantInOperation"`
	ComponentProductDeliverFromPartyInOperation              *int     `json:"ComponentProductDeliverFromPartyInOperation"`
	ComponentProductDeliverFromPlantInOperation              *string  `json:"ComponentProductDeliverFromPlantInOperation"`
	ComponentProductRequirementDateInOperation               *string  `json:"ComponentProductRequirementDateInOperation"`
	ComponentProductRequirementTimeInOperation               *string  `json:"ComponentProductRequirementTimeInOperation"`
	ComponentProductPlannedQuantityInBaseUnitInOperation     *float32 `json:"ComponentProductPlannedQuantityInBaseUnitInOperation"`
	ComponentProductPlannedQuantityInDeliveryUnitInOperation *float32 `json:"ComponentProductPlannedQuantityInDeliveryUnitInOperation"`
	ComponentProductPlannedScrapInPercentInOperation         *float32 `json:"ComponentProductPlannedScrapInPercentInOperation"`
	ComponentProductBaseUnit                                 *string  `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                             *string  `json:"ComponentProductDeliveryUnit"`
	ComponentProductIsMarkedForBackflush                     *bool    `json:"ComponentProductIsMarkedForBackflush"`
	MRPArea                                                  *string  `json:"MRPArea"`
	MRPController                                            *string  `json:"MRPController"`
	ProductionVersion                                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                                    *int     `json:"ProductionVersionItem"`
	ComponentProductReservation                              *int     `json:"ComponentProductReservation"`
	ComponentProductReservationItem                          *int     `json:"ComponentProductReservationItem"`
	PlannedOrderIsReleased                                   *bool    `json:"PlannedOrderIsReleased"`
	CreationDate                                             *string  `json:"CreationDate"`
	CreationTime                                             *string  `json:"CreationTime"`
	LastChangeDate                                           *string  `json:"LastChangeDate"`
	LastChangeTime                                           *string  `json:"LastChangeTime"`
	IsMarkedForDeletion                                      *bool    `json:"IsMarkedForDeletion"`
}
